title = "Think Product by Jiri"
author = "Jiri De Jagere"
copyright = "Copyright (c) 2017 Jiri De Jagere. All Rights Reserved."

baseURL = "https://jiridj.be/"
relativeURLs = true

languageCode = "en-us"

enableEmoji = true

preserveTaxonomyNames = true

[permaLinks]
  post = "/:section/:slug/"

[taxonomies]
   tag = "tags"

[blackfriday]
  plainIDAnchors = true
  hrefTargetBlank = true

[params]
  justComments = "e210eda4-2303-4680-a514-0ca9365f63d1"
  reCaptcha = false